omron:
  omron_goal_client:
    ros__parameters:
      map: "/omron/map" #topic
      odom: "/omron/odom" #topic
      frame: "omron/base_footprint" #tf

  controller_manager:
    ros__parameters:
      omron_state_broadcaster:
        type: omron/OmronStateBroadcaster
  
      joint_trajectory_controller:
          type: joint_trajectory_controller/JointTrajectoryController
  
      joint_state_broadcaster:
          type: joint_state_broadcaster/JointStateBroadcaster
          
      robotiq_gripper_controller:
        type: position_controllers/GripperActionController
        
      robotiq_activation_controller:
        type: robotiq_controllers/RobotiqActivationController
          
      

  omron_state_broadcaster:
    ros__parameters:
      tf:
        use_tf: true
        to: "omron/base_footprint"
        from: "omron/map"
        odom: "omron/odom"
      interfaces:
        velocity:
          prefix: "omron_base/velocity"
          command:
            - "linear/velocity"
            - "angular/velocity"
          states:
            - "linear/velocity"
            - "angular/velocity"
        pose:
          prefix: "omron_base/pose"
          states:
          - "linear/x"
          - "linear/y"
          - "angular/z"
        reference:
          prefix: "omron_base/reference"
          command:
            - "linear/x"
      #          - "linear/y"
      #          - "linear/z"
      #          - "angular/x"
      #          - "angular/y"
            - "angular/z"

  joint_trajectory_controller:
    ros__parameters:
      joints:
        - omron/joint_1
        - omron/joint_2
        - omron/joint_3
        - omron/joint_4
        - omron/joint_5
        - omron/joint_6
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      
  # Gripper Robotiq
  robotiq_gripper_controller:
    ros__parameters:
      default: true
      joint: omron/finger_joint

  robotiq_activation_controller:
    ros__parameters:
      default: true
