/omron/omron_goal_client:
  ros__parameters:
    map: "/omron/map" #topic
    odom: "/omron/odom" #topic
    frame: "omron/base_link" #tf

/omron/controller_manager:
  ros__parameters:
    omron_state_broadcaster:
      type: omron/OmronStateBroadcaster

/omron/omron_state_broadcaster:
  ros__parameters:
    tf:
      use_tf: true
      to: "omron/base_link"
      from: "map"
      odom: "omron/odom"
    interfaces:
      velocity:
        prefix: "omron_base/velocity"
        command:
          - "linear/velocity"
          - "angular/velocity"
        states:
          - "linear/velocity"
          - "angular/velocity"
      pose:
        prefix: "omron_base/pose"
        states:
        - "linear/x"
        - "linear/y"
        - "angular/z"
      reference:
        prefix: "omron_base/reference"
        command:
          - "linear/x"
    #          - "linear/y"
    #          - "linear/z"
    #          - "angular/x"
    #          - "angular/y"
          - "angular/z"
  