# Default initial positions for omron_imm's ros2_control fake system

initial_positions:
  omron/joint_1: 0
  omron/joint_2: 0
  omron/joint_3: 0
  omron/joint_4: 0
  omron/joint_5: 0
  omron/joint_6: 0