# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - omron/imm_controller

  omron/imm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - omron/joint_1
      - omron/joint_2
      - omron/joint_3
      - omron/joint_4
      - omron/joint_5
      - omron/joint_6