# MoveIt uses this configuration for controller management
omron:
  moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

  moveit_simple_controller_manager:
    controller_names:
      - omron/joint_trajectory_controller

    omron/joint_trajectory_controller:
      type: FollowJointTrajectory
      joints:
        - omron/joint_1
        - omron/joint_2
        - omron/joint_3
        - omron/joint_4
        - omron/joint_5
        - omron/joint_6
      action_ns: follow_joint_trajectory
      default: true