# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    imm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

imm_controller:
  ros__parameters:
    joints:
      - omron/joint_1
      - omron/joint_2
      - omron/joint_3
      - omron/joint_4
      - omron/joint_5
      - omron/joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity